### ISSUE TITLE
Artifacts are missing legal files

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/orb-gmbal-pfl#17]
as is required and documented in https://www.eclipse.org/projects/handbook/#legaldoc

**Comment by russgold** [comment]
which files, specifically, are missing?

**Comment by lukasj** [comment]
the already referenced document - https://www.eclipse.org/projects/handbook/#legaldoc - lists them in Distribution section:

```
MyFile.jar
 ├── META-INF
 │   ├── NOTICE
 │   └── LICENSE
 └── ...
```

see that document for complete info, I don't want do copy & paste everything, thanks!

**Comment by russgold** [comment]
Fixed by commit 4f6052b7013f41

**Comment by lukasj** [comment]
I don't think fix is correct - does the change make required files included in source jars? I mean we used to follow the pattern where buildhelper-maven-plugin is used, see ie https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/pom.xml#L446 (I'm not trying to say that that's the only correct way)

**Comment by russgold** [comment]
The required files are placed in the binary jars. Build-helper-maven-plugin would also work, although it doesn't seem to allow changing the file names, and you wind up with, for example, LICENSE.md rather than LICENSE.

If that is OK, I can certainly use that plugin instead. But what do you think is not working?

**Comment by lukasj** [comment]
no, this is not fixed. As of 4.1.0, only pfl-basic artifact contains required legal files, the rest (pfl-asm, pfl-basic-tools, pfl-dynamic, pfl-test, pfl-tf and pfl-tf-tools) is still missing it
